## This notebook demonstrate how one can load the csv data and convert into the standard pytorch dataloader, that are able to be use directly for deep learning training pipeline in pytorch

In [1]:
import numpy as np
import pandas as pd
import os
import sys

import torch
print(torch.__version__)


1.7.1


In [2]:
from helpers import brain_data


In [3]:
#For example we want to load subject 1's slided window data with window size of 30s
sub1_file = './data/chunk_data/size_30sec_150ts_stride_3ts/sub_1.csv'

num_chunk_this_window_size = 1488 #the slided window data with window size of 30s has 1488 windows

### Load the data from csv file, return feature array and label array

In [4]:
sub_feature_array, sub_label_array = brain_data.read_subject_csv_binary(sub1_file,  num_chunk_this_window_size=num_chunk_this_window_size)


### convert to dataset object

In [5]:
sub1_dataset = brain_data.brain_dataset(sub_feature_array, sub_label_array)

### convert to dataloader

In [6]:
#set your own settings for the dataloader
batch_size = 10
shuffle = True

In [7]:
sub1_dataloader = torch.utils.data.DataLoader(sub1_dataset, batch_size=batch_size, shuffle=shuffle)

### Now let's look at the dataloader

In [8]:
for i, (data_batch, labels_batch) in enumerate(sub1_dataloader):
    print(labels_batch)

tensor([1, 1, 1, 1, 1, 1, 0, 0, 0, 0])
tensor([0, 0, 1, 0, 0, 1, 0, 1, 0, 1])
tensor([1, 1, 0, 0, 0, 1, 0, 1, 1, 1])
tensor([0, 0, 1, 1, 1, 1, 1, 1, 0, 1])
tensor([0, 1, 0, 1, 0, 1, 0, 1, 1, 0])
tensor([1, 0, 0, 1, 1, 1, 0, 0, 1, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 0])
tensor([1, 1, 1, 1, 0, 1, 0, 1, 0, 1])
tensor([1, 0, 1, 1, 1, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 0, 1, 0, 0, 1, 1, 1])
tensor([0, 0, 0, 1, 1, 0, 1, 1, 1, 0])
tensor([1, 1, 1, 0, 0, 1, 0, 1, 1, 0])
tensor([0, 1, 0, 1, 1, 1, 0, 0, 1, 0])
tensor([1, 1, 1, 0, 1, 1, 1, 1, 0, 0])
tensor([0, 1, 1, 0, 0, 0, 0, 0, 1, 1])
tensor([1, 0, 0, 1, 0, 1, 0, 1, 0, 1])
tensor([0, 1, 1, 0, 0, 0, 1, 1, 0, 1])
tensor([1, 1, 0, 0, 0, 1, 0, 1, 0, 0])
tensor([0, 1, 0, 1, 1, 1, 0, 0, 1, 1])
tensor([0, 0, 1, 0, 1, 0, 0, 0, 1, 1])
tensor([1, 0, 1, 0, 1, 0, 0, 0, 0, 0])
tensor([1, 0, 1, 0, 1, 0, 0, 0, 0, 1])
tensor([1, 0, 0, 1, 0, 1, 1, 1, 0, 1])
tensor([1, 0, 1, 0, 0, 0, 0, 1, 0, 0])
tensor([0, 1, 0, 0, 0, 0, 1, 0, 0, 0])
tensor([1, 0, 1, 1, 0, 0,